#lang pollen

◊(define-meta title "The year so far")
◊(define-meta date "Sunday April 12, 2026")

◊post-title{◊(select-from-metas 'title metas)}
◊post-date{◊(select-from-metas 'date metas)}

It's already April somehow, and I think for the sake of trying to regular maintain some kind of timeline of updates on my (academia/research-related, at least) life, I should give some brief updates on things that have happened to me so far this year.

Honestly, I don't really know what sorts of posts I should continue to populate these pages with. When I was working at eBay, I'd often write these long, rambling rants in my local Obsidian notes about software-related things I felt strongly about, and that's sort of what I thought I might do semi-publicly here instead, along with some more heavy-duty technical nuggets that I found interesting. But now that this is becoming more of a professional site --- I'll actually be a PhD student next year! --- I'm not sure if the opinions and style of that kind of writing is really all that palatable. To be fair, it's not really as if I've been writing that sort of thing here anyways.

There's also the fact that, even just as a baby graduate student (i.e. a clueless MS student), there's a lot more stuff that is just more important for me to do with my time, and it's just hard to write well-organized, reasonably high quality things here consistently. Stuff like reading papers, taking notes on those papers, working on research, etc. are much more important, and take up a lot of time.◊fn[0] Also, taking classes... Things are a bit different now than they were when I set up all this posting infrastructure, back when I was bumming it in NYC after I quit my job.
◊fndef[0]{Who could have anticipated this...}

But speaking of graduate school and PhD programs, here's the biggest piece of academia-related news from the past few months: I'll be starting as a PhD student at Cornell in the fall! I'm very excited. And also very grateful for all the help, support, and completely unwarranted belief that has been bestowed upon me these past couple years.

Maybe this is the kind of thing that posts here will consist of, in lieu of me having any other form of social media: news updates on my (academic) life. But that's kind of lame. Hopefully there will be more interesting stuff too. Something I think is quite cool is when researchers add more context for their published work, along with various things that maybe didn't make a paper, as a longer-form blog post of some kind. I also like ◊link["www.jonmsterling.com/index/"]{Jon Sterling's} blog style, where he mostly just talks about the interesting things he's been thinking about in the past week of work. Of course, this presupposes that (a) I can produce interesting, publishable research and (b) I actually have interesting things to say about research-related topics. Also (c) that I've done work in the past week. So who knows.

Anyway, here's how the months so far this year have gone:
◊items{
◊item{◊strong{January:} started the quarter, didn't go to POPL 2026 because I ran out of savings (sad), taking an OS class and TAing for Caleb's verification class, lots of PhD interviews over Zoom. The interviews were honestly pretty nerve-wracking, but generally went well (at least from my perspective). Cool to talk to some of the researchers in the PL field that I've looked up to for a while, but also felt a bit like a fraud because I don't know anything and it felt like these very smart, very accomplished people could tell that I didn't know anything (maybe uncharitable to myself, but also probably a bit true).}
◊item{◊strong{February:} a few last interviews, Seahawks won the Super Bowl (this one was epic), got an offer from Cornell (this one was also epic, also happened the same week as the Seahawks Super Bowl win), got a few more PhD offers that trickled in towards the end of the month.}
◊item{◊strong{March:} various visit days/weekends for PhD programs, absolute pain in terms of trying to do TA work, finish up our group project for my OS class, and finish up artifact evaluation for OOPSLA 2026, all while traveling and doing PhD vists. Didn't end up submitting anything to OOPSLA 2026 (which was very much expected, but still a bummer). Was cool to visit Indiana for the first time. Santa Cruz is beautiful, but unfortunately quite expensive. End of the quarter was brutal for the reasons listed earlier, but it was fine in the end. Spring break visiting Cornell and then Boston was sort of fun and definitely necessary, but I also wish I could have just stayed home and relaxed. Got to see friends in NYC between visits though, which was great.}
◊item{◊strong{April:} Last quarter at Davis starts, really need to finish up my thesis so I can at least graduate/not embarrass myself.◊fn[2] Decided to accept the Cornell offer. Went to go visit my brother, which I figured I should do at least once while we're both in California. They're graduating college next month, which is crazy to me. I'm hopefully going to graduate from the Davis MS program in two months, which would have been crazy to me 4 years ago (i.e. why in the world would I ever go back to school, and why would I be in Davis), but really just can't happen soon enough for me right now. Really going to try and enjoy this last quarter of being at Davis and doing research with Caleb --- that's something that I definitely will miss a lot when I leave! Also try to hang out more with the people that I like a lot here in Davis. It's a bit wild to me how these last few years have flown by, ever since I got it in my head to try doing the graduate school thing, but I really want to also try and enjoy things as they are, where I am.}
}
◊fndef[2]{I really hope this doesn't end up being painful towards the end! It might though. Oh God, it might.}
